### ISSUE TITLE
You got the hyphen working, but colon is not working well.

### ISSUE THREAD

**Issue by phcoliveira** [orizens/html-extended#2]
A tag like this is working fine:

``` html
<my:tag></my:tag>
```

But the same tag will break if you add a space or newline between the opening and closing tags.

``` html
<my:tag>This is not supposed to be broken</my:tag>
```

Thanks!

**Comment by orizens** [comment]
hi @phcoliveira.  
Thanks for reporting it.  
I commited a new fix for this which seems to fix it:  
![image](https://cloud.githubusercontent.com/assets/878660/8876178/c02e31a0-3226-11e5-9c4e-7ddb5e838813.png)
